const DATA = [
  {
    id: '1',
    title: '10 AM',
    icon: 'cloud',
    temp: 20,
    day: 'Sunday',
    tempmin: 20,
    tempmax: 18,
  },
  {
    id: '2',
    title: '10 AM',
    icon: 'cloud',
    temp: 20,
    day: 'Monday',
    tempmin: 20,
    tempmax: 18,
  },
  {
    id: '3',
    title: '10 AM',
    icon: 'cloud',
    temp: 20,
    day: 'Tuesday',
    tempmin: 20,
    tempmax: 18,
  },
  {
    id: '4',
    title: '10 AM',
    icon: 'cloud',
    temp: 20,
    day: 'Wednesday',
    tempmin: 20,
    tempmax: 18,
  },
  {
    id: '5',
    title: '10 AM',
    icon: 'cloud',
    temp: 20,
    day: 'Thursday',
    tempmin: 20,
    tempmax: 18,
  },
  {
    id: '6',
    title: '10 AM',
    icon: 'cloud',
    temp: 20,
    day: 'Friday',
    tempmin: 20,
    tempmax: 18,
  },
  {
    id: '7',
    title: '10 AM',
    icon: 'cloud',
    temp: 20,
    day: 'Saturday',
    tempmin: 20,
    tempmax: 18,
  },
  {
    id: '8',
    title: '10 AM',
    icon: 'cloud',
    temp: 20,
    day: 'Sunday',
    tempmin: 20,
    tempmax: 18,
  },
  {
    id: '9',
    title: '10 AM',
    icon: 'cloud',
    temp: 20,
    day: 'Monday',
    tempmin: 20,
    tempmax: 18,
  },
  {
    id: '10',
    title: '10 AM',
    icon: 'cloud',
    temp: 20,
    day: 'Tuesday',
    tempmin: 20,
    tempmax: 18,
  },
];

const Current = {
  coord: {
    lon: 77.33,
    lat: 28.58,
  },
  weather: [
    {
      id: 804,
      main: 'Clouds',
      description: 'overcast clouds',
      icon: '04d',
    },
  ],
  base: 'stations',
  main: {
    temp: 310.31,
    feels_like: 311.17,
    temp_min: 310.31,
    temp_max: 310.31,
    pressure: 998,
    humidity: 30,
    sea_level: 998,
    grnd_level: 976,
  },
  visibility: 10000,
  wind: {
    speed: 2.98,
    deg: 295,
    gust: 4.05,
  },
  clouds: {
    all: 86,
  },
  dt: 1626517303,
  sys: {
    type: 1,
    id: 9165,
    country: 'IN',
    sunrise: 1626480220,
    sunset: 1626529774,
  },
  timezone: 19800,
  id: 7279746,
  name: 'Noida',
  cod: 200,
};

const Settings = [
  {
    title: 'Account',
    iconName: 'user',
    iconType: 'feather',
  },
  {
    title: 'Notification',
    iconName: 'bell',
    iconType: 'feather',
  },
  {
    title: 'Dark Mode',
    iconName: 'theme-light-dark',
    iconType: 'material-community',
  },
  {
    title: 'Language',
    iconName: 'language',
    iconType: 'font-awesome',
  },
  {
    title: 'Share',
    iconName: 'share-social-outline',
    iconType: 'ionicon',
  },
  {
    title: 'Terms and Conditions',
    iconName: 'document-text-outline',
    iconType: 'ionicon',
  },
  {
    title: 'Privacy Policy',
    iconName: 'shield-checkmark-outline',
    iconType: 'ionicon',
  },
  {
    title: 'Help',
    iconName: 'help-circle-outline',
    iconType: 'ionicon',
  },
  {
    title: 'About',
    iconName: 'information-circle-outline',
    iconType: 'ionicon',
  },
];

export {DATA, Current, Settings};
